### ISSUE TITLE
Cannot use crisp directly from repository anymore

### ISSUE THREAD

**Issue by fingolfin** [bh11/crisp#1]
[The following of course also applies to irredsol]

With the change in 1f908e95991b3700ecd7258b07cbdaadbb4c2a10, I cannot use crisp directly from its repository anymore, at least not without figuring out how to build it. That's quite a step backwards from my point of view :-(

My guess is that I need to do something like `make VERSION=1.4dev` to get a working crisp. But this then runs into the problem that it seems you hardcoded the assumption that crisp is in $GAPROOT/pkg/crisp -- which it isn't for me. Also, it seems to assume that `htm` directory with certain content already exists. I worked around that by adding

```
GAPROOT=../..
```

to the top of the Makefile, and then changing the `manual.html` target to

```
manual.html:
    ( \
            rm -f htm/*.htm; \
            mkdir -p htm; \
            perl $(GAPROOT)/etc/convert.pl -n CRISP -c -i doc htm; \
            chmod -R a+r htm \
    )
```

That said, perhaps you could provide a default value for `VERSION` in your Makefile, like `dev` or `1.4dev`, so that unsuspecting people can just type `make` to get a working package?

And perhaps the default target could just be `versions`, or `all: versions manual` or so -- this way, people who are not you and do not wish to build a release tarball, just use the package from the repository, would be accomodated.

**Comment by bh11** [comment]
@fingolfin Thanks for your feedback. Looks like at least some paths in manual.tex also need to be updated.

But maybe it makes more sense to add a few prebuilt files (PackageInfo.g, manual.six, maybe README and index.html) so that it's not necessary to do any installation at all. 

I must admit that so far I never considered the git repo a distribution channel.

**Comment by olexandr-konovalov** [comment]
I was going to report this, when I've discovered that @fingolfin already raised this question.

I am setting up a test when package development versions are cloned into some GAP Docker container (latest release/stable/master branch) and then their standard test is run, and I've got into trouble there by assuming that crisp and irredsol clones pass tests, when actually GAP was using their releases (see https://github.com/gap-packages/gap-docker-pkg-tests-master-devel/issues/9). 

I've now fixed that, but for crisp and irredsol that means that the test fails because there clone is not runnable after cloning it. You will see this at https://travis-ci.org/gap-packages/gap-docker-pkg-tests-master-devel after the build at https://travis-ci.org/gap-packages/gap-docker-pkg-tests-master-devel/builds/423717550 will be finished.

**Comment by bh11** [comment]
@alex-konovalov This should be fixed (and the issue closed). The problem with the travis test might be that it expects a PackageInfo.g file before calling "make". As mentioned above, all auto-generated files are (intentionally) missing from the repo.

**Comment by olexandr-konovalov** [comment]
@bh11 no, the test uses `PackageInfo.g` at a later stage, but it simply never calls `make` (e.g. see the log [here](https://travis-ci.org/gap-packages/gap-docker-pkg-tests-master-devel/jobs/423717650)) because it does not see neither `autogen.sh` nor `configure.sh` hence decides that a package does not have to be built (see https://github.com/gap-packages/gap-docker-pkg-tests-master-devel/blob/master/ci.sh). I have added a note on crisp and irredsol to https://github.com/gap-packages/gap-docker-pkg-tests-master-devel/issues/7 where I plan to deal with this.

**Comment by olexandr-konovalov** [comment]
@bh11 @fingolfin it is now possible to have a script called `prerequisites.sh` which will be run before attempting to building a package. Semigroups provided such script to clone and build libsemigroups in https://github.com/gap-packages/Semigroups/pull/515, and I've updated testing setup in https://github.com/gap-packages/gap-docker-pkg-tests-master-devel/pull/6, and now the test of semigroups pass: https://travis-ci.org/gap-packages/gap-docker-pkg-tests-master-devel/jobs/428393254.

If you can add `prerequisites.sh` which will make the clone usable, I will be able to test it properly at https://travis-ci.org/gap-packages/gap-docker-pkg-tests-master-devel

**Comment by fingolfin** [comment]
The way virtually every other package deals with this is to not generate `PackageInfo.g`, but rather use it as the authoritative source for the package version and release date. Plus, inside `PackageInfo.g`, one can do things like this to avoid repeating the version and date:
```diff
-ArchiveURL := "http://www.icm.tu-bs.de/~bhoeflin/crisp/crisp-CRISP_VERSION",
+ArchiveURL := Concatenation("http://www.icm.tu-bs.de/~bhoeflin/crisp/crisp/", ~.Version),
```
Extracting the version from `PackageInfo.g` can be done safely by calling `gap`, see e.g. https://github.com/gap-system/GitHubPagesForGAP/blob/gh-pages/update.g which does that to regenerate websites. Personally, I'd also not bother encoding a package version and date in the README (esp. if nothing else changes), but that's probably a matter of taste.


@alex-konovalov It is unclear to me who is calling `prerequisites.sh` -- your Travis/Docker tests? If packages are "supposed" to have such a thing, it really should be documented somewhere, no?

**Comment by olexandr-konovalov** [comment]
yes, crisp and irredsol are the only two packages I've discovered (among those which match three conditions: hosted on github; known to me; have `tst` directory). While `prerequisites.sh` now allows for an easy solution, I agree with @fingolfin that in the long run just having a version in PackageInfo.g is more preferable. I also removed versions/dates from my READMEs, to not to be bothered by making trivial updates there each time.

@fingolfin only in the Travis/Docker test which gets a container and clones there package repository from GitHub, instead of using the "official" package release. E.g. https://github.com/gap-packages/gap-docker-pkg-tests-master-devel. So, this is interesting only to packages matching the three conditions above. I will document it in the README at https://github.com/gap-packages/gap-docker-pkg-tests-master-devel and will invite package authors then.

**Comment by olexandr-konovalov** [comment]
@bh11 I've seen that you made commit https://github.com/bh11/crisp/commit/d04ea0000bad3cad05c3b3462bacb94ceaf9c771 but this does not help me: as you can see at https://travis-ci.org/gap-packages/gap-docker-pkg-tests-stable-4.10-devel/jobs/429243601 it tries to build manuals and fails. I think the same will be happening when a user will run `bin/BuildPackages.sh` script to install packages, if they don't have all tools installed. We do not require users to rebuild package manuals. 

My suggestion would be to not to build manuals by default when `make` is called, but have a separate target `make manuals` or `make doc` which you will call when making a release, if you wish to continue to use more or less your current setup (for packages using GitHubPagesForGAP+ReleaseTools it is a bit different, and I think simpler).

**Comment by bh11** [comment]
The package does come with pre-built manuals, of course. No building/installation required.

In the repo, I follow the rule to ignore autogenerated files. If you want to use the repository for automatic testing, you'll have to build the package, including the manuals, otherwise you won't have the required index files for the help system.

If the GAP test installation does not supply gapmacro.tex and related files, I suggest you just drop crisp and irredsol dev versions from automatic testing, and use the released packages instead.

**Comment by olexandr-konovalov** [comment]
> The package does come with pre-built manuals, of course. No building/installation required.

That's exactly how it should be, of course. These files are autogenerated and there is no need to keep them under version control. 

> In the repo, I follow the rule to ignore autogenerated files. If you want to use the repository for automatic testing, you'll have to build the package, including the manuals, otherwise you won't have the required index files for the help system.

Is there a test in `tst/*.tst` for that, which will fail in this case? There are many files in `tst`, could you please point it out. 

> If the GAP test installation does not supply gapmacro.tex and related files, I suggest you just drop crisp and irredsol dev versions from automatic testing, and use the released packages instead.

Of course, I am already testing released packages, e.g. in https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.10 and both crisp and irredsol run well there. But I want also to run a test with dev versions, for the reasons explained in the README at https://github.com/gap-packages/gap-docker-pkg-tests-master-devel. 

Second, I think that your current setup would lead to manuals being built by `bin/BuildPackages.sh` and this is not desirable, that's why I am suggesting `make doc` or `make manuals` or `make release` to do that instead of default `make`.
